- company: "Nvidia | Spatial Intelligence Lab"
  date: "2025"
  position: "Research Intern"
  hosts: "Mikaela Angelina Uy, Nicolas Sharp"
  logo: "/assets/img/experience_logo/nvidia.png"

- company: "Adobe | 3D Graphics and Interactive Design Lab"
  date: "2024"
  position: "Research Intern"
  hosts: "Zhiqin Chen, Vova Kim, Siddhartha Chaudhuri"
  logo: "/assets/img/experience_logo/adobe.png"

- company: "Microsoft Research Asia | Internet Graphics Group"
  date: "2022"
  position: "Research Intern"
  hosts: "Hao Pan"
  logo: "/assets/img/experience_logo/microsoft.png"

- company: "Amazon | Amazon Web Services"
  date: "2021"
  position: "Software Development Engineer Intern"
  logo: "/assets/img/experience_logo/aws.png"